name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: ${{ gitea.server_url }}
  IMAGE_NAME: ${{ gitea.repository }}
  # Container name for deployment
  CONTAINER_NAME: scrouge

jobs:
  # ============================================
  # Quality Gate: Lint, Type Check, and Test
  # ============================================
  quality:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Biome lint and format check
        run: bun run lint

      - name: Type check
        run: bun run typecheck

      - name: Run unit tests
        run: bun test tests/

  # ============================================
  # Build Docker Image
  # ============================================
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: quality
    # Only build on main branch pushes, not PRs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    outputs:
      image_tag: ${{ steps.meta.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Generate image metadata
        id: meta
        run: |
          SHORT_SHA=$(echo "${{ gitea.sha }}" | cut -c1-7)
          echo "tag=${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "full_tag=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ gitea.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push Docker image
        run: |
          # Build with all required build args
          docker build \
            --build-arg VITE_CONVEX_URL=${{ secrets.VITE_CONVEX_URL }} \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tag }} \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
            .

          # Push both tags
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tag }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  # ============================================
  # Deploy with Health Checks and Rollback
  # ============================================
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    environment: production
    steps:
      - name: Deploy via SSH with health check
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            set -e

            REGISTRY="${{ env.REGISTRY }}"
            IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
            TAG="${{ needs.build.outputs.image_tag }}"
            CONTAINER="${{ env.CONTAINER_NAME }}"
            BACKUP_CONTAINER="${CONTAINER}-backup"

            echo "=== Deploying ${IMAGE}:${TAG} ==="

            # Login to registry (use stdin to avoid password in logs)
            echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ${REGISTRY} -u ${{ gitea.actor }} --password-stdin

            # Pull new image
            docker pull ${IMAGE}:${TAG}

            # Backup current container if running
            if docker ps -q -f name=${CONTAINER} | grep -q .; then
              echo "=== Backing up current container ==="
              docker rename ${CONTAINER} ${BACKUP_CONTAINER} || true
              docker stop ${BACKUP_CONTAINER} || true
            fi

            # Remove old backup if exists
            docker rm ${BACKUP_CONTAINER}-old 2>/dev/null || true

            # Start new container
            echo "=== Starting new container ==="
            docker run -d \
              --name ${CONTAINER} \
              --restart unless-stopped \
              -p 3000:3000 \
              -e CONVEX_URL=${{ secrets.CONVEX_URL }} \
              -e NODE_ENV=production \
              --health-cmd="curl -f http://localhost:3000/health || exit 1" \
              --health-interval=10s \
              --health-timeout=5s \
              --health-retries=3 \
              --health-start-period=30s \
              ${IMAGE}:${TAG}

            # Wait for health check
            echo "=== Waiting for health check ==="
            ATTEMPTS=0
            MAX_ATTEMPTS=12
            while [ $ATTEMPTS -lt $MAX_ATTEMPTS ]; do
              HEALTH=$(docker inspect --format='{{.State.Health.Status}}' ${CONTAINER} 2>/dev/null || echo "starting")
              echo "Health status: ${HEALTH} (attempt $((ATTEMPTS+1))/${MAX_ATTEMPTS})"

              if [ "${HEALTH}" = "healthy" ]; then
                echo "=== Container is healthy! ==="
                # Remove backup container
                docker rm ${BACKUP_CONTAINER} 2>/dev/null || true
                echo "=== Deployment successful ==="
                exit 0
              fi

              if [ "${HEALTH}" = "unhealthy" ]; then
                echo "=== Container is unhealthy, rolling back ==="
                break
              fi

              ATTEMPTS=$((ATTEMPTS+1))
              sleep 5
            done

            # Rollback on failure
            echo "=== Rolling back to previous version ==="
            docker stop ${CONTAINER} 2>/dev/null || true
            docker rm ${CONTAINER} 2>/dev/null || true

            if docker ps -a -q -f name=${BACKUP_CONTAINER} | grep -q .; then
              docker rename ${BACKUP_CONTAINER} ${CONTAINER}
              docker start ${CONTAINER}
              echo "=== Rollback complete ==="
            else
              echo "=== No backup available, deployment failed ==="
            fi

            exit 1

      - name: Notify deployment status
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "Deployment successful: ${{ needs.build.outputs.image_tag }}"
          else
            echo "Deployment failed or rolled back"
          fi

  # ============================================
  # Cleanup old images (weekly)
  # ============================================
  cleanup:
    name: Cleanup Old Images
    runs-on: ubuntu-latest
    needs: deploy
    if: success()
    steps:
      - name: Cleanup old images on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            # Keep only last 5 images
            docker images "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" --format "{{.ID}} {{.CreatedAt}}" | \
              sort -k2 -r | \
              tail -n +6 | \
              awk '{print $1}' | \
              xargs -r docker rmi || true

            # Prune unused images
            docker image prune -f
